name: semgrep-pro
on:
  push:
    branches: [master]
  pull_request: {}
  workflow_dispatch: {}
  schedule:
    - cron: "28 6 * * 4"
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.label || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
jobs:
  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
      image: semgrep/semgrep
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v5
      - run: semgrep ci --sarif-output=semgrep.sarif
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
      - uses: github/codeql-action/upload-sarif@16140ae1a102900babc80a33c44059580f687047 # v4
        if: always()
        with:
          sarif_file: semgrep.sarif
